spring:
  profiles:
    active: docker

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: core-service
              uri: http://localhost:8081
              predicates:
                - Path=/core/**

server:
  port: 8080