spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/mydb
    username: postgres
    password: 1234

  flyway:
    url: jdbc:postgresql://localhost:5432/mydb
    user: postgres
    password: 1234

  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    root: INFO
    jcn.yourorder: DEBUG
    org.springframework.r2dbc: DEBUG
    io.r2dbc.postgresql: DEBUG
    org.springframework.cloud.gateway: TRACE
