spring:
  application:
    name: auth-gateway

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: auth-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "jcn.yourorder"

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  profiles:
    active: dev