spring:
  application:
    name: auth-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: customer-service
              uri: http://localhost:8082
              predicates:
                - Path=/customer/**
            - id: seller-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/seller/**
  profiles:
    active: docker

server:
  port: 8080
